name: Sync to GitLab
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Sync to GitLab
        uses: wangchucheng/git-repo-sync@v0.1.0
        with:
          target-url: ${{ secrets.GITLAB_URL }}
          target-username: ${{ secrets.GITLAB_USERNAME }}
          target-token: ${{ secrets.GITLAB_TOKEN }}
