name: Trigger GitLab CI

on:
  push:
    branches: [ main ]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab pipeline
        run: |
          curl -X POST \
            -F token=${{ secrets.GITLAB_TRIGGER_TOKEN }} \
            -F ref=main \
            https://gitlab.com/api/v4/projects/75342724/trigger/pipeline
